### ISSUE TITLE
Can't send blob file

### ISSUE THREAD

**Issue by JenGL** [peers/peerjs#540]
I'm trying to send a file drag and dropped in a div, but i always get this error.
Error: Type "function Blob() { [native code] }" not yet supported.

```
sendFiles(fileList) {
    Array.from(fileList).forEach(file => {
        const blob = new Blob([file], { type: file.type });
        this.conn.send({
          op: operation.FILE,
          file: blob,
          filename: file.name,
          filetype: file.type
        });
    });
  }
```

I tryed to send directly File Object, Blob or ArrayBuffer. Got always the same error

**Comment by kidandcat** [comment]
Convert it to base64

**Comment by JenGL** [comment]
I found a lot of posts on internet that use peerjs to send blob.
like here: https://blog.bitsrc.io/use-webrtc-and-peerjs-to-build-an-image-sharing-app-f8163b6a6266
or here: https://www.sitepoint.com/file-sharing-component-react/

may be it was working on older release ?

**Comment by kidandcat** [comment]
Which browsers are you using?

**Comment by JenGL** [comment]
laste Chrome version: Version 75.0.3770.100 (official Build) (64 bit)

**Comment by kidandcat** [comment]
Sorry, I re-read your first message. The error "Error: Type "function Blob() { [native code] }" not yet supported." looks like is not related at all to WebRTC. Could you paste more code? if it is private, you can write me an email instead kidandcat@gmail.com

**Comment by JenGL** [comment]
this is the onDrop handler (drag and drop any file in a div)

`
onDrop(evt) {
        const el = evt.target;
        el.classList.remove("drop_here");
        this.peer.sendFiles(evt.dataTransfer.files);
        evt.preventDefault();
        evt.stopPropagation();
        return false;
      }
`
this is the sendFiles() implementation

`
sendFiles(fileList) {
    Array.from(fileList).forEach(file => {
        const blob = new Blob([file], { type: file.type });
       // const blob = file; <- tried this too given that file is a blob
        this.conn.send({                  // this.conn is a workin connection to another peer
                                                     // this.conn.send("hi") here correctly working
          op: operation.FILE,
          file: blob,
          filename: file.name,
          filetype: file.type
        });
    });
  }
`

**Comment by kidandcat** [comment]
Do you get the exac "Error: Type "function Blob() { [native code] }" not yet supported." error if you try sending the File directly? (without calling Blob constructor)

**Comment by JenGL** [comment]
sender fiddle: https://jsfiddle.net/vg14skj8/
receiver fiddle: https://jsfiddle.net/ygeb5093/

File or Blob object throws the same error yes.

**Comment by RealHandy** [comment]
Could you be having this issue? https://github.com/peers/peerjs/issues/536

**Comment by JenGL** [comment]
y it's probably the same issue.

**Comment by afrokick** [comment]
@RealHandy I had create new pull request to our fork https://github.com/peers/js-binarypack/pull/7
We'll use our fork in PeerJS

**Comment by JenGL** [comment]
@afrokick if you are going to update the PeerJS v1 can you also add this patch : https://github.com/peers/peerjs/issues/347

**Comment by afrokick** [comment]
> @afrokick if you are going to update the PeerJS v1 can you also add this patch : #347

could you please create pr? I'll merge it

**Comment by JenGL** [comment]
done: https://github.com/peers/peerjs/pull/550

**Comment by JenGL** [comment]
Blob problem is present also in v1.0.2
receiver: https://jsfiddle.net/rjno0sz8/
sender: https://jsfiddle.net/po5xyhk7/

**Comment by afrokick** [comment]
We didn't fix it in 1.0.2, only #550 

@JenGL could you please help us with fix it via pr?

**Comment by JenGL** [comment]
> @RealHandy I had create new pull request to our fork [peers/js-binarypack#7](https://github.com/peers/js-binarypack/pull/7)
> We'll use our fork in PeerJS

Shoulddn't this fix that problem ?

**Comment by JenGL** [comment]
I create two different pr: one for the fork of bynarypacker-js and anotherone for the peerjs with the update lib (I had to copy the builded js lib inside peerjs)
