### ISSUE TITLE
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/peerjs.min.js.map

### ISSUE THREAD

**Issue by nick0702y** [peers/peerjs#721]
peerjs version used 1.3.1

Error loading peerjs.min.js.map 
Error Report
---------------
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/peerjs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Please help with this issue

**Comment by Nour490-code** [comment]
Same Problem

**Comment by AlyNeumann** [comment]
Same problem

**Comment by germanvalentino** [comment]
same problem

**Comment by abhay27chauhan** [comment]
@szareian thanks

**Comment by Akmal-M** [comment]
same problem with facepalm)

**Comment by 2Gunz** [comment]
same problem

**Comment by AJOO7** [comment]
same problem

**Comment by derd1011** [comment]
same problem

**Comment by karimk123** [comment]
Is this still not fixed??

**Comment by dcarlson661** [comment]
@szareian Thanks!

**Comment by GiuseppeSaponieri** [comment]
? So

**Comment by dcarlson661** [comment]
Hi,
Because I didn't realize that it was a session only and when I restarted things and reconnected the message came back.  So not knowing it was session only I started looking for other problems.  Until I realized I had to go back into settings and re-check the box.
That's all. 
DC

**Comment by germanvalentino** [comment]
I have the same problem, it seems to be not solved yet. I think nobady is working on this issue.
German

**Comment by Guama1239** [comment]
El mismo problemo!!!

**Comment by zahra-ove** [comment]
same problem!

**Comment by karimk123** [comment]
Is it fixed?

**Comment by Seniorprogrammer-123** [comment]
me too

**Comment by ThePlatinum** [comment]
update on the fix please, it's killing here

**Comment by DhruvDutta** [comment]
same problem!

**Comment by byhyakimaro** [comment]
drug, this problem exists in 2020 and has nothing so far

**Comment by Kana-creator** [comment]
DevTools failed to load SourceMap: Could not load content for https://unpkg.com/peerjs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Anny one to help me out with this issue

**Comment by levlaz** [comment]
Hello, 

First, I think its worth noting that if you are having a problem with the peerJS library itself there is a 99.999% chance it has nothing to do with this particular issue. 

This error happens because your browser is unable to load the source map file from unpkg. This should have no bearing on your ability to use this library at all. The source map is strictly used for debugging within a web browser. 

The specific reason why this is happening is related to this issue from parcel which is what this project uses for creating the JS bundle: https://github.com/parcel-bundler/parcel/issues/3000 

If you look at the bottom of the [peerjs bundle](https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map) you will see this line: 

```
//# sourceMappingURL=/peerjs.min.js.map
```

The `sourceMappingURL` should not have ` /` because it is causing the reference url to go to `https://unpkg.com/peerjs.min.js.map` (which 404s) instead of `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map` where it actually lives. 

I think the proper way to fix this is by changing the configuration of parcel to make the URL relative instead of absolute. 

In the meantime, if you actually need to load the source map files you can [do it manually in chrome](https://stackoverflow.com/questions/34087143/load-separate-sourcemap-file-in-chrome-dev-tools) using the full sourcemap url: `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map`

**Comment by advokrat** [comment]
Hey, I am in need of include this source map in a project, but it needs to load seamlessly on any device. Is there any workaround so that I can use this peerJS library robustly?

**Comment by bagaswap111** [comment]
Have same problem here. i am using safari for running development. might be caused by the browser suport (?). i've tried on ms edge too, though the result is the same, just like here
<img width="376" alt="image" src="https://user-images.githubusercontent.com/81802233/127174118-713a1172-047b-4cdd-b222-7a3a02b67207.png">

may be would try this solution, however i havent got it clear how to change the parcel.
> Hello,
> 
> First, I think its worth noting that if you are having a problem with the peerJS library itself there is a 99.999% chance it has nothing to do with this particular issue.
> 
> This error happens because your browser is unable to load the source map file from unpkg. This should have no bearing on your ability to use this library at all. The source map is strictly used for debugging within a web browser.
> 
> The specific reason why this is happening is related to this issue from parcel which is what this project uses for creating the JS bundle: [parcel-bundler/parcel#3000](https://github.com/parcel-bundler/parcel/issues/3000)
> 
> If you look at the bottom of the [peerjs bundle](https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map) you will see this line:
> 
> ```
> //# sourceMappingURL=/peerjs.min.js.map
> ```
> 
> The `sourceMappingURL` should not have ` /` because it is causing the reference url to go to `https://unpkg.com/peerjs.min.js.map` (which 404s) instead of `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map` where it actually lives.
> 
> I think the proper way to fix this is by changing the configuration of parcel to make the URL relative instead of absolute.
> 
> In the meantime, if you actually need to load the source map files you can [do it manually in chrome](https://stackoverflow.com/questions/34087143/load-separate-sourcemap-file-in-chrome-dev-tools) using the full sourcemap url: `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map`

any one have tried?

**Comment by SecretSenator** [comment]
> Have same problem here. i am using safari for running development. might be caused by the browser suport (?). i've tried on ms edge too, though the result is the same, just like here
> <img alt="image" width="376" src="https://user-images.githubusercontent.com/81802233/127174118-713a1172-047b-4cdd-b222-7a3a02b67207.png">
> 
> may be would try this solution, however i havent got it clear how to change the parcel.
> 
> > Hello,
> > First, I think its worth noting that if you are having a problem with the peerJS library itself there is a 99.999% chance it has nothing to do with this particular issue.
> > This error happens because your browser is unable to load the source map file from unpkg. This should have no bearing on your ability to use this library at all. The source map is strictly used for debugging within a web browser.
> > The specific reason why this is happening is related to this issue from parcel which is what this project uses for creating the JS bundle: [parcel-bundler/parcel#3000](https://github.com/parcel-bundler/parcel/issues/3000)
> > If you look at the bottom of the [peerjs bundle](https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map) you will see this line:
> > ```
> > //# sourceMappingURL=/peerjs.min.js.map
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The `sourceMappingURL` should not have ` /` because it is causing the reference url to go to `https://unpkg.com/peerjs.min.js.map` (which 404s) instead of `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map` where it actually lives.
> > I think the proper way to fix this is by changing the configuration of parcel to make the URL relative instead of absolute.
> > In the meantime, if you actually need to load the source map files you can [do it manually in chrome](https://stackoverflow.com/questions/34087143/load-separate-sourcemap-file-in-chrome-dev-tools) using the full sourcemap url: `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map`
> 
> any one have tried?

Is the problem fixed now?

**Comment by selfcontrol7** [comment]
Please, until now, there is still no fix for this issue?

**Comment by Santoshah** [comment]
How to fixed this issue ? I even disabled the sourcemap in my chrome but still facing the same issue.

**Comment by Santoshah** [comment]
Hey Guys I think i have found the solution. 

I was having same error as title as you can see in my screenshot.

![image](https://user-images.githubusercontent.com/3863771/154938127-9d247ce6-609e-4247-8842-60bd4cf44577.png)

my peer commnad running at 3001
```
santoshshah@192 video-webrtc % peerjs --port 3001
Started PeerServer on ::, port: 3001, path: / (v. 0.6.1)
```

As the error is pointing towards  `localhost:443` in the screenshot, I change the port of peerjs from `3001` to `443`

`peerjs --port 443`

```
santoshshah@192 video-webrtc % peerjs --port 443 
Started PeerServer on ::, port: 443, path: / (v. 0.6.1)
Client connected: 7f449c07-dc4c-4b65-b164-8f6f503520d5
```

and refresh my browser and got this running message. I got `Client connected: 7f449c07-dc4c-4b65-b164-8f6f503520d5`. 

The error message went away but I still see warning of peerjs source map warning.

![image](https://user-images.githubusercontent.com/3863771/154939145-542f60f4-2dd6-45fd-830f-c0f67854266b.png)

**Comment by alainpaulinn** [comment]
Hello
I solved this issue by downloading `https://unpkg.com/peerjs@1.3.2/dist/peerjs.min.js.map` file instead of loading from the url, i included the file in my Javascript folder,
and at the end of the code in this file I removed `//# sourceMappingURL=/peerjs.min.js.map` and replaced it by `//# sourceMappingURL=peerjs.min.js.map`
The warning should disappear
