### ISSUE TITLE
Safari: Attempted to assign to readonly property 

### ISSUE THREAD

**Issue by FeSeason** [peers/peerjs#800]
In  Safari browser receive client，has this error

Safari:  13.1.3 (15609.4.1)

![image](https://user-images.githubusercontent.com/12840843/110272099-51786000-8004-11eb-92e2-54f5c21df81e.png)

## Steps of recurrence

receivePage:  https://jmcker.github.io/Peer-to-Peer-Cue-System/receive.html

sendPage: https://jmcker.github.io/Peer-to-Peer-Cue-System/send.html

### Step 1

open sendPage in chrome browers (chrome: 89.0.4389.82)

### Step 2

open receivePage in safari browers (safari: 13.1.3 (15609.4.1))

### Step 3

![image](https://user-images.githubusercontent.com/12840843/110272502-5689df00-8005-11eb-9a74-8a2d151e4c92.png)

**Comment by jordanaustin** [comment]
I'm having he same problem but I noticed this was only happening when trying to connect to the Safari host from a Chromium based browser on chrome 89. Using your examples here I opened a Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1186456

**Comment by jordanaustin** [comment]
I put up a PR that fixes this issue: #806. Here's hoping for a fast merge and a patch version of `peerjs` released

**Comment by FeSeason** [comment]
@jordanaustin 

Based on this PR, an emergency version was issued, rename `peerjs-patch` 

https://www.npmjs.com/package/peerjs-patch

### Please wait for the official version if it is not urgent. !!!

**Comment by afrokick** [comment]
fixed in 1.3.2

**Comment by andread95** [comment]
Hello there, I'm still facing this issue when trying to call from Chrome Android to Safari (Desktop or iOS) but It does work viceversa.
Already updated PeerJS to 1.3.2 
I didn't face any problem from Chrome Desktop to Safari (Desktop or iOS).

Inspecting the console the problem seems to be on the answer method "call.answer(stream)" and returns "webrtc" as error.

![Schermata 2021-03-24 alle 18 11 03](https://user-images.githubusercontent.com/8678965/112353780-60316900-8ccc-11eb-8b1b-b36fb9710eff.png)

**Comment by fdsea** [comment]
Hi! Using v1.3.1 I catch the error described above, in v1.3.2 the error - OperationsError: Expects at Least 2 fields. Error is "webrtc" type. Any ideas how to fix it?

**Comment by maxpavlov** [comment]
Just to share my experience. I encountered this error on Safari when using peerjs 1.3.1. I wanted to check if 1.3.2 fixes it, assumed all done, tested and the problem was still there. Thanks to the rather vivid versioning info I have across my compiled application, I noticed that due to manual error I was still using peerjs 1.3.1. 

Once I made sure the code used 1.3.2 - the problem was gone.

**Comment by rushglen** [comment]
Thank you! using 1.3.2 it now works with Safari (iphone 12 pro, iOS 15.1) talking to chrome desktop.
