### ISSUE TITLE
Answer don`t work in safari

### ISSUE THREAD

**Issue by fdsea** [peers/peerjs#817]
Hi! Using v1.3.1 I catch the error ' Attempted to assign to readonly property', in v1.3.2 the error - OperationsError: Expects at Least 2 fields. Error is "webrtc" type.  Any ideas how to fix it?

**Comment by fdsea** [comment]
Errors occur if you call in Safari with Chrome, when you call with FF everything works

**Comment by andread95** [comment]
Same here. I commented on issue #800

**Comment by fdsea** [comment]
Hi all, I fixed the bug but want to make sure it is defeated :) Tested it on all devices available to me and it works, but I want to be completely sure, can anyone help me with this? https://github.com/fdsea/peerjs/tree/fix817

**Comment by andread95** [comment]
I'm still facing some issue on Safari. When a call is started from Chrome Android to Safari (Desktop or iOS) it does not work and returns "webrtc" as error ( #800 )

**Comment by fdsea** [comment]
Its work on iPad only...

**Comment by andread95** [comment]
It doesn't work on Safari iPad neither..
